use std::collections::HashMap;
use std::time::Duration;
use uuid::Uuid;

/// Configuration for spawning a worker. Domain-level only -- no PIDs, no process concepts.
#[derive(Debug, Clone)]
pub struct WorkerSpawnConfig {
    pub run_id: Uuid,
    pub task_id: Uuid,
    pub instance_id: Uuid,
    /// Pre-generated by the scheduler at claim time.
    pub session_id: Uuid,
    /// The task prompt/spec to send to the coding agent.
    pub prompt: String,
    /// Hard kill after this duration.
    pub timeout: Duration,
    /// Expected heartbeat frequency.
    pub heartbeat_interval: Duration,
    /// Path to the git worktree for this run.
    pub worktree_path: String,
    /// Environment variables for the worker process.
    pub environment: HashMap<String, String>,
}

/// Logical handle to a running worker. No PIDs exposed at the domain level.
#[derive(Debug, Clone)]
pub struct WorkerHandle {
    pub session_id: Uuid,
    pub run_id: Uuid,
    /// Path to the stdout log file.
    pub log_stdout: String,
    /// Path to the stderr log file.
    pub log_stderr: String,
}

/// Errors from worker operations.
#[derive(Debug)]
pub enum WorkerError {
    /// Worker spawn failed (e.g., binary not found, I/O error).
    SpawnFailed(String),
    /// Worker with the given session_id was not found.
    NotFound(Uuid),
    /// Worker with the given session_id is already running.
    AlreadyRunning(Uuid),
    /// Generic I/O error during worker operations.
    IoError(String),
}

impl std::fmt::Display for WorkerError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::SpawnFailed(msg) => write!(f, "worker spawn failed: {msg}"),
            Self::NotFound(id) => write!(f, "worker not found: {id}"),
            Self::AlreadyRunning(id) => write!(f, "worker already running: {id}"),
            Self::IoError(msg) => write!(f, "worker IO error: {msg}"),
        }
    }
}

impl std::error::Error for WorkerError {}

impl From<std::io::Error> for WorkerError {
    fn from(err: std::io::Error) -> Self {
        Self::IoError(err.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn spawn_config_fields_accessible() {
        let config = WorkerSpawnConfig {
            run_id: Uuid::new_v4(),
            task_id: Uuid::new_v4(),
            instance_id: Uuid::new_v4(),
            session_id: Uuid::new_v4(),
            prompt: "implement feature X".to_string(),
            timeout: Duration::from_secs(3600),
            heartbeat_interval: Duration::from_secs(30),
            worktree_path: "/tmp/worktrees/run-1".to_string(),
            environment: HashMap::from([("KEY".to_string(), "VALUE".to_string())]),
        };

        let _: Uuid = config.run_id;
        let _: Uuid = config.task_id;
        let _: Uuid = config.instance_id;
        let _: Uuid = config.session_id;
        let _: &str = &config.prompt;
        let _: Duration = config.timeout;
        let _: Duration = config.heartbeat_interval;
        let _: &str = &config.worktree_path;
        assert_eq!(config.environment.get("KEY").unwrap(), "VALUE");
    }

    #[test]
    fn spawn_config_clone() {
        let config = WorkerSpawnConfig {
            run_id: Uuid::new_v4(),
            task_id: Uuid::new_v4(),
            instance_id: Uuid::new_v4(),
            session_id: Uuid::new_v4(),
            prompt: "test prompt".to_string(),
            timeout: Duration::from_secs(600),
            heartbeat_interval: Duration::from_secs(10),
            worktree_path: "/tmp/wt".to_string(),
            environment: HashMap::new(),
        };
        let cloned = config.clone();
        assert_eq!(config.run_id, cloned.run_id);
        assert_eq!(config.session_id, cloned.session_id);
        assert_eq!(config.prompt, cloned.prompt);
        assert_eq!(config.timeout, cloned.timeout);
    }

    #[test]
    fn spawn_config_debug() {
        let config = WorkerSpawnConfig {
            run_id: Uuid::new_v4(),
            task_id: Uuid::new_v4(),
            instance_id: Uuid::new_v4(),
            session_id: Uuid::new_v4(),
            prompt: "test".to_string(),
            timeout: Duration::from_secs(60),
            heartbeat_interval: Duration::from_secs(5),
            worktree_path: "/tmp".to_string(),
            environment: HashMap::new(),
        };
        let debug = format!("{config:?}");
        assert!(debug.contains("WorkerSpawnConfig"));
        assert!(debug.contains("run_id"));
        assert!(debug.contains("session_id"));
        assert!(debug.contains("prompt"));
    }

    #[test]
    fn worker_handle_fields_accessible() {
        let handle = WorkerHandle {
            session_id: Uuid::new_v4(),
            run_id: Uuid::new_v4(),
            log_stdout: "/data/logs/stdout.log".to_string(),
            log_stderr: "/data/logs/stderr.log".to_string(),
        };

        let _: Uuid = handle.session_id;
        let _: Uuid = handle.run_id;
        let _: &str = &handle.log_stdout;
        let _: &str = &handle.log_stderr;
    }

    #[test]
    fn worker_handle_clone() {
        let handle = WorkerHandle {
            session_id: Uuid::new_v4(),
            run_id: Uuid::new_v4(),
            log_stdout: "/data/stdout.log".to_string(),
            log_stderr: "/data/stderr.log".to_string(),
        };
        let cloned = handle.clone();
        assert_eq!(handle.session_id, cloned.session_id);
        assert_eq!(handle.run_id, cloned.run_id);
        assert_eq!(handle.log_stdout, cloned.log_stdout);
        assert_eq!(handle.log_stderr, cloned.log_stderr);
    }

    #[test]
    fn worker_handle_debug() {
        let handle = WorkerHandle {
            session_id: Uuid::new_v4(),
            run_id: Uuid::new_v4(),
            log_stdout: "/tmp/stdout.log".to_string(),
            log_stderr: "/tmp/stderr.log".to_string(),
        };
        let debug = format!("{handle:?}");
        assert!(debug.contains("WorkerHandle"));
        assert!(debug.contains("session_id"));
        assert!(debug.contains("log_stdout"));
    }

    #[test]
    fn worker_error_display_spawn_failed() {
        let err = WorkerError::SpawnFailed("binary not found".to_string());
        assert_eq!(err.to_string(), "worker spawn failed: binary not found");
    }

    #[test]
    fn worker_error_display_not_found() {
        let id = Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        let err = WorkerError::NotFound(id);
        assert_eq!(
            err.to_string(),
            "worker not found: 550e8400-e29b-41d4-a716-446655440000"
        );
    }

    #[test]
    fn worker_error_display_already_running() {
        let id = Uuid::new_v4();
        let err = WorkerError::AlreadyRunning(id);
        let display = err.to_string();
        assert!(display.starts_with("worker already running: "));
        assert!(display.contains(&id.to_string()));
    }

    #[test]
    fn worker_error_display_io_error() {
        let err = WorkerError::IoError("permission denied".to_string());
        assert_eq!(err.to_string(), "worker IO error: permission denied");
    }

    #[test]
    fn worker_error_from_io_error() {
        let io_err = std::io::Error::new(std::io::ErrorKind::NotFound, "file not found");
        let worker_err = WorkerError::from(io_err);
        assert!(matches!(worker_err, WorkerError::IoError(_)));
        assert!(worker_err.to_string().contains("file not found"));
    }

    #[test]
    fn worker_error_from_io_error_preserves_message() {
        let io_err = std::io::Error::new(
            std::io::ErrorKind::PermissionDenied,
            "cannot write to /var/data",
        );
        let worker_err: WorkerError = io_err.into();
        assert!(worker_err.to_string().contains("cannot write to /var/data"));
    }

    #[test]
    fn worker_error_is_std_error() {
        let err: Box<dyn std::error::Error> =
            Box::new(WorkerError::SpawnFailed("test".to_string()));
        assert!(err.to_string().contains("worker spawn failed"));
    }

    #[test]
    fn worker_error_debug() {
        let err = WorkerError::SpawnFailed("test".to_string());
        let debug = format!("{err:?}");
        assert!(debug.contains("SpawnFailed"));
        assert!(debug.contains("test"));
    }

    #[test]
    fn spawn_config_with_empty_environment() {
        let config = WorkerSpawnConfig {
            run_id: Uuid::new_v4(),
            task_id: Uuid::new_v4(),
            instance_id: Uuid::new_v4(),
            session_id: Uuid::new_v4(),
            prompt: "".to_string(),
            timeout: Duration::from_secs(0),
            heartbeat_interval: Duration::from_secs(0),
            worktree_path: "".to_string(),
            environment: HashMap::new(),
        };
        assert!(config.environment.is_empty());
    }

    #[test]
    fn spawn_config_with_multiple_env_vars() {
        let mut env = HashMap::new();
        env.insert("OPENCLAW_SESSION_ID".to_string(), "abc".to_string());
        env.insert("OPENCLAW_RUN_ID".to_string(), "def".to_string());
        env.insert("OPENCLAW_INSTANCE_ID".to_string(), "ghi".to_string());

        let config = WorkerSpawnConfig {
            run_id: Uuid::new_v4(),
            task_id: Uuid::new_v4(),
            instance_id: Uuid::new_v4(),
            session_id: Uuid::new_v4(),
            prompt: "test".to_string(),
            timeout: Duration::from_secs(60),
            heartbeat_interval: Duration::from_secs(5),
            worktree_path: "/tmp".to_string(),
            environment: env,
        };
        assert_eq!(config.environment.len(), 3);
        assert_eq!(
            config.environment.get("OPENCLAW_SESSION_ID").unwrap(),
            "abc"
        );
    }
}
